server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/customers/**

        - id: orchestrator-service
          uri: lb://ORCHESTRATOR-SERVICE
          predicates:
            - Path=/orchestrator/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/categories/**, /products/**, /reviews/**, /images/**

        - id: content-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/blogs/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:3001
              - http://localhost:3002
              - http://localhost:3003
              - http://localhost:3004
              - http://localhost:3005
              - http://localhost:3006
              - http://localhost:8761
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
