server:
  port: 8090

spring:
  application:
    name: report-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EcommerceDB
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  sales-service:
    url: http://localhost:8081
  user-service:
    url: http://localhost:8082
  product-service:
    url: http://localhost:8083